### ISSUE TITLE
g2 performance degradation

### ISSUE THREAD

**Issue by kgerheiser** [NOAA-EMC/NCEPLIBS-g2#104]
There are reports of g2's performance with between versions 3.1 and 3.4.

There have been few actual code changes so I suspect it's this commit which removes the `save` attribute and deallocates/re-allocates an array if it's already already allocated.

https://github.com/NOAA-EMC/NCEPLIBS-g2/commit/c51c8f0cf2beaa574eecf2e2bbbfaa990c2406f4

https://github.com/NOAA-EMC/NCEPLIBS-g2/pull/52

**Comment by kgerheiser** [comment]
@BoiVuong-NOAA can you comment on this? 

In the PR you thought it wouldn't result in performance issues.

https://github.com/NOAA-EMC/NCEPLIBS-g2/pull/52#issuecomment-856186552

How can we fix the performance issue while also allowing re-used `LUGB` values? Is that possible? I think they're mutually exclusive. In that case, what behavior is correct?

**Comment by kgerheiser** [comment]
> Kyle,
> We need to put back the SAVE and check for condition of grib index file. We will not allow user to open the same unit file (LUGB).
> If we do not have SAVE, the routine getgb2 will continue to generate the index file for each time its call to search for fields in grib2 file.


@BoiVuong-NOAA can you comment in this issue here?

What about this line?

https://github.com/NOAA-EMC/NCEPLIBS-g2/blob/7e78071c76e23132acf1d5dd75d0250953bd6a25/src/getidx.f#L101

**Comment by BoiVuong-NOAA** [comment]
Kyle,

We can to use that line without SAVE.  You need to test with Scott's 
test case and another test case with same unit file number.

**Comment by BijuThomas-NOAA** [comment]
@kgerheiser,
Let me know if you want to do a test with our code

**Comment by kgerheiser** [comment]
@BijuThomas-NOAA just saw this after sending you an email. Yes, I would like to try this out.

**Comment by BijuThomas-NOAA** [comment]
@kgerheiser, My tests with the HAFS system on Orion is successful with the g2 build in /home/gkyle/NCEPLIBS-g2/build/install
Thanks,

**Comment by kgerheiser** [comment]
Unfortunately, there was a mixup in the libraries used in testing, and the actual culprit is:

https://github.com/NOAA-EMC/NCEPLIBS-g2/blob/4a45dbf1a083b0d0d441678e1058a199fc03c7d0/src/getidx.f#L101

This block will have to be removed so that the index isn't regenerated every time. The performance penalty is too large.

@BijuThomas-NOAA  this will break your code where you repeat `LUGB`, but see this note.

```
Users can force a regeneration of an
index. If LUGI equals LUGB, the index will be regenerated from 
the data in file LUGB. If LUGI is less than zero, then the index
is re read from index file abs(lugi).
```

You can re-use LUGB and force re-generation of the index. 


@BoiVuong-NOAA what do you think?

**Comment by BoiVuong-NOAA** [comment]
User can use new unit file number for each time open grib2 file.
