### ISSUE TITLE
Function baread() from bacio is called from src/getgb2r.f, but bacio is neither found nor linked...

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-g2#154]
In subroutine GETGB2R() there are calls to the bacio library:

For example note the calls to BAREAD() around line 206:

```
C  READ AND UNPACK BIT_MAP, IF PRESENT
      IF ( gfld%ibmap.eq.0.OR.gfld%ibmap.eq.254 ) THEN
         ISKIP=LSKIP+SKIP6
         CALL BAREAD(LUGB,ISKIP,4,LREAD,CSIZE)    ! GET LENGTH OF SECTION
         CALL G2_GBYTEC(CSIZE,ILEN,0,32)
         ALLOCATE(CTEMP(ILEN))
         CALL BAREAD(LUGB,ISKIP,ILEN,LREAD,CTEMP)  ! READ IN SECTION
```

This seems to indicate that this subroutine is never used anywhere. If so, we should drop it...

@BoiVuong-NOAA and @Hang-Lei-NOAA do you know anything about this? Was there a past dependency on bacio? Is the subroutine GETGB2R() expected to work by anyone?

**Comment by BoiVuong-NOAA** [comment]
I do not know it has used anywhere.

**Comment by edwardhartnett** [comment]
@kgerheiser do you know anything about dependency of g2 on bacio?

**Comment by edwardhartnett** [comment]
I thought this meant that this subroutine is never used anywhere (because otherwise the user would get link errors). But I think it could still work as part of a program that also linked to the bacio library in some other way. So I suspect this means we need to add a check for the bacio library to the g2 CMakeLists file...

**Comment by Hang-Lei-NOAA** [comment]
I think we should try to drop it. The extra dependency should be reduced.

**Comment by edwardhartnett** [comment]
It was removed here: https://github.com/NOAA-EMC/NCEPLIBS-g2/pull/14

No reason given. But apparently it should not have been removed.

I don't see how we can just drop this function. It could be very important...

**Comment by kgerheiser** [comment]
That does seem to be incorrect behavior

Went through some old emails to find history.

`find_package(bacio)` was added and then @BoiVuong-NOAA had some issues building and told me g2 didn't require g2.

```
CMake Error at src/CMakeLists.txt:39 (add_library):
  Target "g2_d" links to target "bacio::bacio_4" but the target was not                          ----> G2 library does not require BACIO lirbary.  Why do we tell cmake to find BACIO ?
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
```

Interestingly, though, we've had g2 without bacio for over a year, and it has been installed on WCOSS2 with everyone testing their applications for production, and it hasn't come up...

**Comment by edwardhartnett** [comment]
I would feel better if I had some idea of what applications are using g2. See #155 . Please contribute answers if you know...

**Comment by edwardhartnett** [comment]
Seems to be a fair amount of code involved here. It seems to be all the code relating to reading and writing something called "index files."

Here's a find/grep of baread calls:

```
(base) ed@mikado:~/NCEPLIBS-g2/src$ find . -name '*.f'|xargs grep -i -s baread
./getgb2rp.f:            CALL BAREAD(LUGB,ISKIP+ISKP2,4,LREAD,ctemp)
./getgb2rp.f:            CALL BAREAD(LUGB,ISKIP+ISKP2,LEN2,LREAD,csec2)
./getgb2rp.f:            CALL BAREAD(LUGB,ISKIP+ISKP6,4,LREAD,ctemp)
./getgb2rp.f:         CALL BAREAD(LUGB,ISKIP+ISKP7,4,LREAD,ctemp)
./getgb2rp.f:         CALL BAREAD(LUGB,ISKIP+ISKP7,LEN7,LREAD,csec7)
./getgb2rp.f:            CALL BAREAD(LUGB,ISKIP+ISKP6,4,LREAD,ctemp)
./getgb2rp.f:            CALL BAREAD(LUGB,ISKIP+ISKP6,LEN6,LREAD,csec6)
./getgb2rp.f:         CALL BAREAD(LUGB,ISKIP,LENG,LREAD,GRIBM)
./getgb2l.f:         CALL BAREAD(LUGB,ISKIP,4,LREAD,CSIZE)    ! GET LENGTH OF SECTION
./getgb2l.f:         CALL BAREAD(LUGB,ISKIP,ILEN,LREAD,CTEMP)  ! READ IN SECTION
./ixgb2.f:      CALL BAREAD(LUGB,LSKIP,IBREAD,LBREAD,CBREAD)
./ixgb2.f:         CALL BAREAD(LUGB,IBSKIP,IBREAD,LBREAD,CBREAD)     
./ixgb2.f:            CALL BAREAD(LUGB,IBSKIP,LENGDS,LBREAD,CGDS)     
./ixgb2.f:            CALL BAREAD(LUGB,IBSKIP,ILNPDS,LBREAD,CINDEX(LINDEX+1))     
./ixgb2.f:            CALL BAREAD(LUGB,IBSKIP,ILNDRS,LBREAD,CINDEX(LINDEX+1))     
./getg2i.f:      CALL BAREAD(LUGI,0,162,LHEAD,CHEAD)
./getg2i.f:          CALL BAREAD(LUGI,NSKP,NLEN,LBUF,CBUF)
./getgb2r.f:         CALL BAREAD(LUGB,ISKIP,4,LREAD,CSIZE)    ! GET LENGTH OF SECTION
./getgb2r.f:         CALL BAREAD(LUGB,ISKIP,ILEN,LREAD,CTEMP)  ! READ IN SECTION
./getgb2r.f:      CALL BAREAD(LUGB,ISKIP,4,LREAD,CSIZE)    ! GET LENGTH OF SECTION
./getgb2r.f:      CALL BAREAD(LUGB,ISKIP,ILEN,LREAD,CTEMP)  ! READ IN SECTION
./getgb2p.f:!         CALL BAREAD(LUGB,ISKIP,LENG,LREAD,GRIBM)
./skgb.f:C>    - 1995-10-31 Mark Iredell add call to baread.
./skgb.f:        CALL BAREAD(LUGB,KS,KN,KZ,Z)
./skgb.f:            CALL BAREAD(LUGB,KS+K+KG-4,4,K4,Z4)
```

Is the idea that all of this code can be removed?

**Comment by BoiVuong-NOAA** [comment]
I did not recall that g2 did notrequire bacio, w3emc and wnco libraries.

**Comment by BoiVuong-NOAA** [comment]
All models in production are using G2 to read and write grib2 files in post processing.

**Comment by kgerheiser** [comment]
But it's also possible they already link to bacio and they don't use CMake to find dependencies.

**Comment by Hang-Lei-NOAA** [comment]
Build of grib_util is also using g2 lib

**Comment by edwardhartnett** [comment]
@BoiVuong-NOAA can you be more specific? When you say all models, what GitHub repos do you mean?

**Comment by kgerheiser** [comment]
https://github.com/NOAA-EMC/NCEPLIBS-grib_util/blob/develop/CMakeLists.txt

uses bacio

https://github.com/NOAA-EMC/UPP/blob/728bdf04568fb01071834e818cd5a47b92522a9a/CMakeLists.txt#L46

uses bacio

https://github.com/NOAA-EMC/UFS_UTILS/blob/69e009fb6e3547d42385c3e9bd8a2871ebfa137e/CMakeLists.txt#L58

uses bacio

**Comment by edwardhartnett** [comment]
@BoiVuong-NOAA when I look at ufs-weater-model, I don't see an explicit dependency on NCEPLIBS-g2. (It does depend on UPP however...)

**Comment by edwardhartnett** [comment]
OK, with all these important user applications using NCEPLIBS-g2, are we really ready to drop a bunch of functions? How do we know that won't break anything?

**Comment by kgerheiser** [comment]
I think the correct behavior should be to search for bacio. If the libraries ever get interfaces or we use shared libraries the current setup won't work.

**Comment by edwardhartnett** [comment]
OK, so I will add bacio back to the CMakeLists.txt file...
