### ISSUE TITLE
Do we know users of NCEPLIBS-g2?

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-g2#155]
What other applications or libraries at NOAA use NCEPLIBS-g2?

I will document them in the README...

**Comment by kgerheiser** [comment]
g2 is used in a lot of places. Went through some interactions I've had in regards to g2:

UFS_UTILS, WW3, hwrf, global_workflow (maybe for UFS_UTILS?), UPP, and MDL.

**Comment by Hang-Lei-NOAA** [comment]
UPP is the main.

**Comment by edwardhartnett** [comment]
@kgerheiser is there a GitHub site for HWRF and MDL?

**Comment by Hang-Lei-NOAA** [comment]
There is a HWRF https://github.com/NCAR/HWRFdev
