### ISSUE TITLE
gf_free function change g2/v3.4.1 vs. g2/v2.5.0

### ISSUE THREAD

**Issue by BoCui-NOAA** [NOAA-EMC/NCEPLIBS-g2#172]
@YanLuo-NOAA @JiayiPeng-NOAA @arunchawla-NOAA 
Compare the two gf_free routines, g2/v2.5.0 vs. g2/v3.4.1 .   The old gf_free use to nullify a pointer and the newer one deallocates it.  Such a change will cause the segmentation fault error for some programs after "call gf_free(gfld). 

Here is  an example,  after  "saving" gfld pointer to gfldo then  go to free gfld. It is actually "deallocating" the space that gfldo is pointing to.  So, glfdo is now pointing to an empty space, next time when access it (glfdo), the data is gone, which cause the job to fail. 

Yan Luo and  I am working on  NAEFS transition using g2/3.4.1. If you plan to update the G2 library, please create a new version based on g2/3.4.1. Thanks!

Bo

**Comment by arunchawla-NOAA** [comment]
@Hang-Lei-NOAA @kgerheiser and @edwardhartnett 

This issue is blocking NAEFS transition. Can you help ? 

@BoCui-NOAA can you also point to an example where you are trying to use this ?

**Comment by BoCui-NOAA** [comment]
I copied the source code, data input and build.ver in one directoryon Cactus:
/lfs/h2/emc/vpppg/noscrub/Bo.Cui/test_gefs_bias_gen

Just type "build.sh WCOSS2", it will compile code and run the executable.

**Comment by kgerheiser** [comment]
Have you tried g2 v3.4.5 (I believe it's available on Cactus). There were some problems with `getidx`, which sounds related to this.

**Comment by BoCui-NOAA** [comment]
The code on Cray are saved at Luna:

/gpfs/hps3/ptmp/Bo.Cui/test_gefs_bias_gen

To build the executable, please type

./build.sh WCOSS_C
 
The g2 lib used is: /gpfs/hps/nco/ops/nwprod/lib/modulefiles/g2-intel/2.5.0

**Comment by edwardhartnett** [comment]
So you want gf_free to just nullify the pointer?

Then how will the memory be deallocated?

**Comment by arunchawla-NOAA** [comment]
I am trying to understand the use case for moving to a different pointer and then trying to free the memory. Am I missing something here ?

**Comment by BoCui-NOAA** [comment]
> 
> 
> Have you tried g2 v3.4.5 (I believe it's available on Cactus). There were some problems with `getidx`, which sounds related to this.

I tried all the 3 versions available, didn't work.

**Comment by edwardhartnett** [comment]
Well here is the code from gf_free:

```
!>    This subroutine frees up memory that was used to store
!>    array values in derived type gribfield.
!>
!>    ### Program History Log
!>    Date | Programmer | Comments
!>    -----|------------|--------- 
!>    2000-05-26 | Stephen Gilbert | Modified from getg1s to work with grib2
!>    2012-12-11 | Boi Vuong | initialize an undefine pointers
!>    2015-10-29 | Boi Vuong | Deallocate pointers in derived type gribfield
!>
!>    @param gfld derived type gribfield (defined in module grib_mod).
!>      
!>    @author Stephen Gilbert @date 2000-05-26
!>

      subroutine gf_free(gfld)

      use grib_mod
    
      type(gribfield) :: gfld

      if (associated(gfld%idsect)) then
         !nullify(gfld%idsect)
         deallocate(gfld%idsect,stat=is)
         !print *,'gfld%idsect: ',is
      endif
      nullify(gfld%idsect)

      if (associated(gfld%local)) then
         ! nullify(gfld%local)
         deallocate(gfld%local,stat=is)
         !print *,'gfld%local: ',is
      endif
      nullify(gfld%local)

```

**Comment by edwardhartnett** [comment]
OK, first thing to note is that the remaining nullify() call is incorrect, as it refers to disassociated pointer, and it should only be used on pointers have been associated, according to the docs.

Also it is unneeded, as deallocate will also nullify the pointer.

But if we change it back to just nullify, the memory will leak. Which seems like it's contrary to the name of this function. ;-)

**Comment by kgerheiser** [comment]
Hmm, ok maybe not related to `getidx`. But @edwardhartnett's interpretation seems correct. I would expect a `_free` function to free up the memory (deallocate). Are you calling `gf_free` yourself, or is it being called internally?

**Comment by arunchawla-NOAA** [comment]
@BoCui-NOAA can you point to the NAEFS repo where the error is happening ?

**Comment by BoCui-NOAA** [comment]
> 
> 
> @BoCui-NOAA can you point to the NAEFS repo where the error is happening ?

https://github.com/NOAA-EMC/NAEFS/blob/develop/sorc/gefs_bias_gen.fd/gefs_bias_gen.f90

line 249

**Comment by kgerheiser** [comment]
Seems like you shouldn't call `gf_free` until you're actually done using the resources

**Comment by BoCui-NOAA** [comment]
I am think the solution;

put an if statement around the gf_free (line 249) on that line.  If 2 files are not available then don't call gf_free, because I will use the same pointer for both,then do gf_free(gfldo) and gfld at the end, this is fine.

**Comment by BoCui-NOAA** [comment]
After discussing with @YanLuo-NOAA and @JiayiPeng-NOAA, We chose to update our codes to use the new g2 library on WCOSS2. Thank you for your reply and explanation of the new g2 lib routine function.
