### ISSUE TITLE
Fix code warnings

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-g2#180]
We have some warnings in the code:
```
[ 82%] Building C object src/CMakeFiles/g2_d_c.dir/dec_jpeg2000.c.o
cd /home/ed/NCEPLIBS-g2/b/src && /usr/bin/cc -DLINUX -D__64BIT__ -I/usr/local/jasper-2.0.33/include -I/usr/include/libpng16 -g  -ggdb -Wall -MD -MT src/CMakeFiles/g2_d_c.dir/dec_jpeg2000.c.o -MF CMakeFiles/g2_d_c.dir/dec_jpeg2000.c.o.d -o CMakeFiles/g2_d_c.dir/dec_jpeg2000.c.o -c /home/ed/NCEPLIBS-g2/src/dec_jpeg2000.c
/home/ed/NCEPLIBS-g2/src/dec_jpeg2000.c: In function ‘dec_jpeg2000_’:
/home/ed/NCEPLIBS-g2/src/dec_jpeg2000.c:45:22: warning: unused variable ‘cmpt’ [-Wunused-variable]
   45 |     jas_image_cmpt_t cmpt, *pcmpt;
      |                      ^~~~
/home/ed/NCEPLIBS-g2/src/dec_jpeg2000.c:44:31: warning: unused variable ‘istream’ [-Wunused-variable]
   44 |     jas_stream_t *jpcstream, *istream;
      |                               ^~~~~~~
/home/ed/NCEPLIBS-g2/src/dec_jpeg2000.c:42:20: warning: unused variable ‘n’ [-Wunused-variable]
   42 |     g2int i, j, k, n;
      |                    ^

```

and

```
/home/ed/NCEPLIBS-g2/src/enc_png.c:86:9: warning: unused variable ‘do_nothing’ [-Wunused-variable]
   86 |    int *do_nothing=NULL;
      |         ^~~~~~~~~~

```

and

```
/home/runner/work/NCEPLIBS-g2/NCEPLIBS-g2/g2/src/g2grids.f:124:0:

  124 |                 prev%next => gtemp      ! points to the new entry,
      | 

```

**Comment by edwardhartnett** [comment]
Actually I think the last one is a bug in the code.

In g2grids.f we have:

`          type(g2grid),pointer :: prev
`
and

```
             if ( count .eq. 1 ) then
                gridlist => gtemp
             else                       ! make sure previous entry in list
                prev%next => gtemp      ! points to the new entry,
             endif
             prev => gtemp

```

So I think the warning is correct. If count .ne. 1, then this code will try and use the prev pointer before it has been initialized.

@Hang-Lei-NOAA and @BrianCurtis-NOAA do you concur? What should be done here?

**Comment by Hang-Lei-NOAA** [comment]
Yes, it looks like the code is working, but not safe.
As the comments indicated, has to make sure previous entry in list.

**Comment by BrianCurtis-NOAA** [comment]
`count` is initialized as 0, then increments before this call, so the first count that reaches here will be 1. I see the warning message isn't there, so what can I assume it's warning us about? We can add a check on the count <=0 to stop if that happens, but will that clear the warning?

**Comment by edwardhartnett** [comment]
THe warning is that prev may be used before it is initialized...

**Comment by BrianCurtis-NOAA** [comment]
can we initialize the pointer to `NULL` ?

**Comment by edwardhartnett** [comment]
That would eliminate the warning, but if that code path is ever followed, it will attempt to dereference a null pointer. Which is also not right.

The question is: how do we write a test so that count = 2? 

Once we have that test, we can decide how to fix the code...

Or is it the case that count can never be anything other than 1?

**Comment by BrianCurtis-NOAA** [comment]
count will always be 1 when it first hits that section. I've tried thinking of ways to make it not 1 when it first hits that section and i can not.

**Comment by edwardhartnett** [comment]
OK, I have changed that code to:

```
             prev => gtemp
             if ( count .eq. 1 ) then
                gridlist => gtemp
             else                       ! make sure previous entry in list
                prev%next => gtemp      ! points to the new entry,
             endif

```
