### ISSUE TITLE
compack calculates lcpack incorrectly for a real(8) length 4 fld with '45.0' as last value.

### ISSUE THREAD

**Issue by BrianCurtis-NOAA** [NOAA-EMC/NCEPLIBS-g2#193]
Using the test `test_compack.f90` in `tests` in repo `https://github.com/BrianCurtis-NOAA/NCEPLIBS-g2/tree/test/compack` shows this bug.

Use a different value for the last item in the array causes the test to pass. There may be other values that it fails with but `45.0` specifically causes a failure where lcpack is 3 and not 4.

**Comment by edwardhartnett** [comment]
You have some commented out test code to demonstrate this? Where is it?

**Comment by BrianCurtis-NOAA** [comment]
> You have some commented out test code to demonstrate this? Where is it?

Please look at my first comment. Direct link: https://github.com/BrianCurtis-NOAA/NCEPLIBS-g2/blob/test/compack/tests/test_compack.f90

**Comment by BrianCurtis-NOAA** [comment]
I will comment out the CMakeLists.txt entry for the PR

**Comment by BrianCurtis-NOAA** [comment]
This bug is demonstrated in PR #185

**Comment by BrianCurtis-NOAA** [comment]
Looks like the fix for this bug was taken care of in #185. Closing
