### ISSUE TITLE
bug fix for g2grid.f90

### ISSUE THREAD

**Issue by Hang-Lei-NOAA** [NOAA-EMC/NCEPLIBS-g2#211]
The Fortran function defined in this code reports error under GNU compiler. 
  integer function readgrids(lunit)

At line 81 of file /home/Hang.Lei/noscrub/docus/feature/unittest1/src/g2grids.F90 (unit = 15, file = 'testdata_g2grids')
Fortran runtime error: Sequential READ or WRITE not allowed after EOF marker, possibly use REWIND or BACKSPACE

Error termination. Backtrace:
#0  0x7f4aed17a5dd in data_transfer_init
        at /tmp/Role.Apps/spack-stage/spack-stage-gcc-9.2.0-wqdecm4rkyyhejagxwmnabt6lscgm45d/spack-src/libgfortran/io/transfer.c:3007
#1  0x401110 in __g2grids_MOD_readgrids
        at /home/Hang.Lei/noscrub/docus/feature/unittest1/src/g2grids.F90:81
#2  0x4018cd in __g2grids_MOD_getgridbynum
        at /home/Hang.Lei/noscrub/docus/feature/unittest1/src/g2grids.F90:169
#3  0x400e5c in ???
#4  0x400c5c in ???
#5  0x7f4aec435554 in ???
#6  0x400c8c in ???
#7  0xffffffffffffffff in ???

**Comment by Hang-Lei-NOAA** [comment]
After investigate this issue, it is found that GNU compiler suggestion is reasonable:
In the code: line 81
       read(lunit,end=999,fmt='(a)') cline
However, the 999 line is:
999    readgrids=count

Count actually is the return value. It could not be used as the end of the file.
Correction should be:
999  backspace(lunit)

**Comment by edwardhartnett** [comment]
Can you rename this issue to something more informative? What is the bug that has been found?

Also, it looks like you also found some memory leaks? Can you please enter an additional issue for that? Memory leaks are important fixes (i.e. worthy of notice by end users) so we need to make sure it's well documented what memory bugs we found and fixed in each release...

**Comment by Hang-Lei-NOAA** [comment]
Hi, Edward

Okay, I will do.
Bug is easy to fix, but the memory leak is difficult.
The test runs fine on both intel and gnu machines. But ci test under gcc
shows memory leaks.
I am still trying to finger out what the issue it is.

Thanks,
Hang
