### ISSUE TITLE
Add w3emc dependency in support of gdt2gds.F90 which is used by grib_util

### ISSUE THREAD

**Issue by BrianCurtis-NOAA** [NOAA-EMC/NCEPLIBS-g2#229]
While writing a unit test for the gdt2gds.F90 code, I noticed that it uses w3emc calls for https://github.com/NOAA-EMC/NCEPLIBS-w3emc/blob/develop/src/w3fi71.f and https://github.com/NOAA-EMC/NCEPLIBS-w3emc/blob/develop/src/r63w72.f at the following two locations:

https://github.com/NOAA-EMC/NCEPLIBS-g2/blob/9a52944bb58f77cd6bb88252f00e41f8c98af552/src/gdt2gds.F90#L344

and

https://github.com/NOAA-EMC/NCEPLIBS-g2/blob/9a52944bb58f77cd6bb88252f00e41f8c98af552/src/gdt2gds.F90#L364

There is currently no w3emc dependency inside g2. Also I would assume nobody is using that code considering the missing dependency has been around for a long time.

We should remove it.

**Comment by edwardhartnett** [comment]
OK, this also will then require dependencies on nemsio, sigio, and netCDF. Yikes!

**Comment by kgerheiser** [comment]
w3emc has no dependency but bacio once gblevents was removed.

**Comment by edwardhartnett** [comment]
OK, great! I was looking at an older version of w3emc. I will update...

**Comment by BrianCurtis-NOAA** [comment]
I commented in the closed PR, so i'll add this here too: @kgerheiser So if we have a call in gdt2gds that uses w3emc functions but doesn't add that dep in CMake, would we not be doing things wrong in some way? Should we add a dep on w3emc since g2 hosts that file? Should we move that file somewhere else?

**Comment by BrianCurtis-NOAA** [comment]
Maybe this file should be where copygb/copygb2 is?

**Comment by edwardhartnett** [comment]
@BrianCurtis-NOAA I think that would be a good suggestion if we knew for sure that was the only place it is used. But I guess we don't know that. :-(

So I will add the dependency of w3emc. Fortunately due to the good work resolving the glbevents problem, that's easier than it used to be...
