### ISSUE TITLE
what is the difference between getg2i() and getg2ir()

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-g2#244]
We have:

`subroutine getg2ir(lugb, msk1, msk2, mnum, cbuf, nlen, nnum, nmess, iret)
`
and also

`SUBROUTINE GETG2I(LUGI,CBUF,NLEN,NNUM,IRET)
`
They seem to do the same thing. Does anyone know the history here?

@BoiVuong-NOAA @GeorgeGayno-NOAA @Hang-Lei-NOAA can you shed any light on this?

**Comment by Hang-Lei-NOAA** [comment]
One is for int, one for real.

**Comment by BoiVuong-NOAA** [comment]
I do not know the history of these routines.  However, one (getg2i.f) reads an index file and one (getg2ir.f) creates an index file.

**Comment by Hang-Lei-NOAA** [comment]
I was reading wrong codes files. But after reading both correct ones. 
I think Boi is correct. getg2i.f is much simpler than the other. It just read out the index.

**Comment by edwardhartnett** [comment]
OK, thanks for the answers. I am writing tests for these functions...
