### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-g2#26]
Our CI testing does literally nothing for this project. So the good news is, it won't be hard to make it better! ;-)

**Comment by edwardhartnett** [comment]
@Hang-Lei-NOAA and @BoiVuong-NOAA are there any GRIB2 files we can use as samples for tests? That is, some actual data files that are hopefully not too large?

**Comment by BoiVuong-NOAA** [comment]
I create a grib2 file which it has 70 records for testing.  The file size is  52MB
The location is /gpfs/dell2/ptmp/Boi.Vuong/output/for_Ed on MARS

**Comment by edwardhartnett** [comment]
How do you create the file? You have some code to do that?

**Comment by BoiVuong-NOAA** [comment]
No, I do not have any code.  I am using WGRIB2 to extract selected fields from GFS grib2 file.
The syntax is following:

$WGRIB2  gfsfile.grib2 | grep -F text_file | $WGRIB2 -i -grib   new_gfsfile.grib2  gfsmaster.grib2
Where:
-gfsfile.grib2   is any gfs grib2 file (0.25,0.5 or 1.0deg)
-text_file        is a file that contains all TMP, HGT, RH,  etc.     Note: The more fields you have, the filesize will be larger file.

**Comment by edwardhartnett** [comment]
OK, I have found a small GRIB2 file here:
https://nomads.ncep.noaa.gov/pub/data/nccf/com/gfs/prod/gdas.20210922/00/wave/gridded/

Do we think that NCEPLIBS-g2 will be able to read this file?

My first question is how to feed this to g2_info, which takes a buffer not a filename. Is the idea that I open the file and read the whole file into a buffer before calling g2_info()? Surely that cannot work with a giant GRIB2 file.

So given a giant GRIB2 file, how would I use NCEPLIBS-g2 to learn about it? What function would I call first?

**Comment by edwardhartnett** [comment]
The current state of play: 19%
![image](https://user-images.githubusercontent.com/38856240/141493693-96899666-9be2-4010-9c6c-86cefb3ab6e5.png)

**Comment by edwardhartnett** [comment]
After recent tests from @Hang-Lei-NOAA and @BrianCurtis-NOAA were merged, we are now at 37% coverage. Big improvement - almost double since early November, so great work guys.

But keep it up - there are plenty of tests still to write! What this coverage means is 6 out of 10 lines of this crucial software are completely untested. We can and will do better...

![image](https://user-images.githubusercontent.com/38856240/147103119-11272752-d2cf-4ea6-accd-6b403e4c1d13.png)

**Comment by BrianCurtis-NOAA** [comment]
Also the two tests I've added which aren't enabled due to bugs will help that number too.

**Comment by Hang-Lei-NOAA** [comment]
Hi, Edward,
Please help me understand it. In the decode test, the gb_info.f90 actually
is fully called and all possible outcomes of gb_info could come out if data
is wrong, while the chart only shows 72.5%. How can we understand that? and
what could be added to make it 100%?
Thanks,
Hang

**Comment by BrianCurtis-NOAA** [comment]
@Hang-Lei-NOAA If you go download the latest artifact from the build with test coverege (here: https://github.com/NOAA-EMC/NCEPLIBS-g2/actions/runs/1611596368 ) then unzip and double click the .html file you can click through the files. So for gb_info.F90 there are certain sections the test didn't hit that are noted in the red color here:
![Screenshot from 2021-12-22 09-12-39](https://user-images.githubusercontent.com/64433609/147106113-5ab9292c-d93c-4682-af43-5e65b3aab99c.png)
e

**Comment by edwardhartnett** [comment]
@Hang-Lei-NOAA if you check out the C tests, you'll see that I had to rerun the code, after deliberately changing the first char in the message, to check cases where it checks for "GRIB" at the beginning of the message. Similarly, I wrote tests where I change the version of the message, then check to see that's caught, etc. 

Basically, you have to create the error condition, call the code, and check that the correct error code was returned.

**Comment by Hang-Lei-NOAA** [comment]
Thanks, Brain and Edward.

**Comment by edwardhartnett** [comment]
OK we are now at 61%, which is really quite respectable for a Fortran library.

I expect this number to go up a little further when we have stripped out the (untested, in this repo) C code that was copied from g2c.
![Screenshot from 2022-07-29 09-57-12](https://user-images.githubusercontent.com/38856240/181798432-32adf3c4-b831-432c-9df7-da6bf8ac0352.png)

**Comment by edwardhartnett** [comment]
I'm closing this issue for the 3.5.0 release. We made lots of progress with testing in this release!
