### ISSUE TITLE
what is GRIB1 w3fi63 format?

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-g2#277]
In the documentation of gdt2gds.F90 we say:

`!> @param[out] kgds GRIB1 GDS as described in w3fi63 format.
`

Does anyone know what "w3fi63 format" means? Is this a typo? I can find no such format on google, and if google does not know of something, can that something even exist?

@GeorgeGayno-NOAA do you have any idea what this could be?

**Comment by BoiVuong-NOAA** [comment]
I think it is  a typo from developer to use the word "format" to describe an array kgds() in routine w3fi63.f in w3nco library.

**Comment by edwardhartnett** [comment]
OK, thanks for the info. I have updated the docs to reflect this.
