### ISSUE TITLE
some params with identical values for g2_discipline g2_category g2_parameter but different abbreviations

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-g2#309]
In params.F90 we have:

`  data paramlist(1002) /gribparam(255, 255, 10, 3, 200, 'TWLDT')/
`
and

`  data paramlist(404) /gribparam(128, 194, 10, 3, 200, 'SSST')/
`
When I call the function:

`  abbrev = param_get_abbrev(10, 3, 200)
`
I always get the first abbrev. There's no way to get the second one. Seems like this must be a bug...

Also:

```
  data paramlist(900) /gribparam(255, 255, 2, 3, 23, 'LWSNWP')/
  data paramlist(901) /gribparam(255, 255, 2, 3, 23, 'FRSTINX')/
  data paramlist(902) /gribparam(255, 255, 2, 3, 23, 'SNWDEB')/
  data paramlist(903) /gribparam(255, 255, 2, 3, 23, 'SHFLX')/
  data paramlist(904) /gribparam(255, 255, 2, 3, 23, 'SOILDEP')/

```
These parameters have all the same numbers! How is that supposed to work?

@BoiVuong-NOAA and @Hang-Lei-NOAA your opinion would be welcome.

**Comment by BoiVuong-NOAA** [comment]
I forgot to change parameters when I added these parameters.
data paramlist(900) /gribparam(255, 255, 2, 3, 23, 'LWSNWP')/
  data paramlist(901) /gribparam(255, 255, 2, 3, 24, 'FRSTINX')/
  data paramlist(902) /gribparam(255, 255, 2, 3, 25, 'SNWDEB')/
  data paramlist(903) /gribparam(255, 255, 2, 3, 26, 'SHFLX')/
  data paramlist(904) /gribparam(255, 255, 2, 3, 27, 'SOILDEP')/

**Comment by BoiVuong-NOAA** [comment]
This line data paramlist(1002) /gribparam(255, 255, 10, 3, 200, 'TWLDT')/
should be
data paramlist(1002) /gribparam(255, 255, 10, 3, 209, 'TWLDT')/

**Comment by edwardhartnett** [comment]
OK, so should we change:
```
data paramlist(900) /gribparam(255, 255, 2, 3, 23, 'LWSNWP')/
data paramlist(901) /gribparam(255, 255, 2, 3, 24, 'FRSTINX')/
data paramlist(902) /gribparam(255, 255, 2, 3, 25, 'SNWDEB')/
data paramlist(903) /gribparam(255, 255, 2, 3, 26, 'SHFLX')/
data paramlist(904) /gribparam(255, 255, 2, 3, 27, 'SOILDEP')/
```

**Comment by edwardhartnett** [comment]
Also should we fix TWLDT?

Won't that break any existing data files using this parameter?

**Comment by BoiVuong-NOAA** [comment]
It will not break any existing data. I think we can leave it alone.

**Comment by edwardhartnett** [comment]
I have opened a separate issue for TWLDT. 

Should we or should we not change the GRIB1 numbers on these parameters:

```
data paramlist(900) /gribparam(255, 255, 2, 3, 23, 'LWSNWP')/
data paramlist(901) /gribparam(255, 255, 2, 3, 24, 'FRSTINX')/
data paramlist(902) /gribparam(255, 255, 2, 3, 25, 'SNWDEB')/
data paramlist(903) /gribparam(255, 255, 2, 3, 26, 'SHFLX')/
data paramlist(904) /gribparam(255, 255, 2, 3, 27, 'SOILDEP')/

```

which you said you forgot to do when you added them.

If we should not fix this, why not?

**Comment by BoiVuong-NOAA** [comment]
Yes, It was my mistake.  You can fix it if you have a chance to do it.

**Comment by edwardhartnett** [comment]
OK, what should it be instead?

**Comment by BoiVuong-NOAA** [comment]
These are correct one.
data paramlist(901) /gribparam(255, 255, 2, 3, 24, 'FRSTINX')/
data paramlist(902) /gribparam(255, 255, 2, 3, 25, 'SNWDEB')/
data paramlist(903) /gribparam(255, 255, 2, 3, 26, 'SHFLX')/
data paramlist(904) /gribparam(255, 255, 2, 3, 27, 'SOILDEP')/

**Comment by edwardhartnett** [comment]
That is what we already have.

What am I missing?

**Comment by BoiVuong-NOAA** [comment]
I do not think any of missing that you may be omitted.  You need to make sure it match to what we have in GRIB2 tables.

**Comment by edwardhartnett** [comment]
@Hang-Lei-NOAA I could never get this figured out. Do you have any idea what @BoiVuong-NOAA meant?

**Comment by edwardhartnett** [comment]
OK, I'm an idiot. Now I see it. PR forthcoming...

**Comment by Hang-Lei-NOAA** [comment]
You picked out the bug. Boi corrected it. That's what I was understanding.👍
