### ISSUE TITLE
parameter abbreviation MSLSA can never be found because it shares G2 numbers with PRMSL which comes first in the array

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-g2#314]
We have:

`  data paramlist(2) /gribparam(2, 2, 0, 3, 1, 'PRMSL')/
`
and

`  data paramlist(238) /gribparam(2, 128, 0, 3, 1, 'MSLSA')/
`

Note that the GRIB2 discipline, category, and number are the same for both of these.

Since the parameter lookup subroutine starts at the beginning of the list, and returns the first abbreviation with matching G2 numbers, the MSLSA abbreviation can never be returned.

@BoiVuong-NOAA any comments on this one?

**Comment by BoiVuong-NOAA** [comment]
In the past, some user used PRMSL or MSLSA in grib1.  Then, they converted to grib2 and these parameters were in same "0,3,1".
Now, You can combine into one or leave it alone.

**Comment by edwardhartnett** [comment]
OK I think it's best to leave it. I will document this...
