### ISSUE TITLE
identify areas for test improvement

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-g2#35]
Please identify what tests will be written first.

Since we currently have no tests, this should be easy. ;-) Just pick something easy to start with...

@BoiVuong-NOAA please take a look at this and identify where we should start writing tests.

**Comment by BoiVuong-NOAA** [comment]
When should we combine the code from g2tmpl into g2 from nceplibs ?  Then, we start writing test.

**Comment by edwardhartnett** [comment]
Let us start with some tests, then combine the codes. ;-)

**Comment by edwardhartnett** [comment]
First step is to get some small data files (<50 MB) and check them into the repo under the test directory. If we get too many or they get to big we can use FTP site. @BoiVuong-NOAA will start on this in ~2 weeks.

**Comment by edwardhartnett** [comment]
@BoiVuong-NOAA any progress here?

**Comment by BoiVuong-NOAA** [comment]
No progress in G2. I am still working in util_shared and submit RFC to NCO by the end of this week.

**Comment by edwardhartnett** [comment]
What is util_shared? That's a new one to me. ;-)

**Comment by edwardhartnett** [comment]
OK, we have identified some test opportunities: #148 #147 #146 #145 #144 #143
