### ISSUE TITLE
current spack package files does not include dependencies on other NCEPLIBS

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-g2#352]
The g2 spack package file has this:

```
    version("3.4.5", sha256="c18e991c56964953d778632e2d74da13c4e78da35e8d04cb742a2ca4f52737b6")
    version("3.4.3", sha256="679ea99b225f08b168cbf10f4b29f529b5b011232f298a5442ce037ea84de17c")

    depends_on("jasper@:2.0.32")
    depends_on("libpng")

```

This is incorrect, but it was what was in the CMakeLists.txt file. However, g2 is also dependent on other packages, as is now reflected in the CMakeLists.txt file:

```
find_package(bacio REQUIRED)
if(bacio_VERSION LESS 2.5.0)
  add_library(bacio::bacio ALIAS bacio::bacio_4)
endif()
find_package(w3emc 2.9.0 REQUIRED)


```

So we also need bacio and w3emc.

**Comment by arunchawla-NOAA** [comment]
why does the g2 library need bacio and w3emc?

**Comment by edwardhartnett** [comment]
It always had needed these packages, but since everything was always linked together, this was not noticed until recently.

It needs bacio because there are numerous functions that depend on the user opening the file with bacio before calling g2.

It needs w3emc because there are some functions that call these GRIB1 functions as well.

**Comment by edwardhartnett** [comment]
This has been done. Thanks @AlexanderRichert-NOAA !
