### ISSUE TITLE
does not link to g2c static library

### ISSUE THREAD

**Issue by nuitlejour** [NOAA-EMC/NCEPLIBS-g2#354]
I have built g2c static library ONLY by modifying g2c cmakelists.txt, and tried to link g2 with g2c static library.

during g2 cmake configuration time, the following error occurred:

CMake Error at /nceplibs/lib64/cmake/g2c/g2c-config.cmake:32 (get_target_property):
  get_target_property() called with non-existent target "g2c::g2c".
Call Stack (most recent call first):
  CMakeLists.txt:59 (find_package)

It seems that g2 cannot find g2c static library, what can I do?

**Comment by edwardhartnett** [comment]
What versions of g2 and g2c are you using?

I believe that the last release of g2 does not depend on g2c.

In fact we are going through a series of NCEPLIBS releases this month and next which will add better support for shared and static builds. Can you describe what you are trying to achieve?

**Comment by nuitlejour** [comment]
hello, there,

I was trying to build a software called vortex tracker that depends on g2:
https://github.com/NOAA-GFDL/GFDL-VortexTracker

I was trying to make my deliverables cleaner by linking the code with static library of g2, netcdf-4 etc.

I am using the lasted main branch of g2, g2c, bacio to compile the code. 

From the cmakelists.txt of g2, it does depend on g2c. 

There was no problem if I have dynamic version of g2c, but if I build ONLY the static version of g2c, g2 will yield error message mentioned above during configuration time.

**Comment by edwardhartnett** [comment]
OK, I suggest you use the last released version of each package, instead of the develop branch. In the last release of g2, there was no dependency on the g2c library.

There is a new version of g2 coming out shortly, which also does not depend on the g2c library and includes some bugfixes.

**Comment by nuitlejour** [comment]
thank you for the suggestion!
