### ISSUE TITLE
CFSv2 operations encounters errors writing grib2 files with jpeg packing beginning end of Feb 2023

### ISSUE THREAD

**Issue by jack-woollen** [NOAA-EMC/NCEPLIBS-g2#356]
CFSv2 end of month processing for Feb and Mar has encountered errors converting grib1 files into grib2 using jpeg compression. All other compression options work. The error involves skipping some records during the conversion. We think its in the jpeg option since this doesn't happen with the other compression options. This code has run since 2011 and to my knowledge has not had this problem until the last two months. Maybe this is related to the several other jpeg issues noted recently.

**Comment by edwardhartnett** [comment]
I need to develop a test for this, so I need some (hopefully small) same file, and then what do I do to see the problems.

**Comment by jack-woollen** [comment]
A testfile to reproduce the problem is on cactus in /lfs/h2/emc/global/noscrub/Jack.Woollen/egyfix. The output from running this script is below.  Notice the input grib1 file has 482 records and the output grib2 file has 481. The error messages are presumably generated from the g2lib.

jack.woollen@clogin05:/lfs/h2/emc/global/noscrub/Jack.Woollen/egyfix> egyfix2
Resetting modules to system default. Reseting $MODULEPATH back to system default. All extra directories will be removed from $MODULEPATH.

Currently Loaded Modules:
  1) craype-x86-rome     (H)   3) craype-network-ofi (H)   5) intel/19.1.3.304   7) grib_util/1.2.3
  2) libfabric/1.11.0.0. (H)   4) envvar/1.0               6) libjpeg/9c         8) wgrib2/2.0.8

  Where:
   H:  Hidden Module

 

++ OPS=/lfs/h1/ops/prod/com/cfs/v2.3/monthly/cdas.202303/monthly
++ file=egyh01.gdas.202303
++ echo

++ wgrib /lfs/h1/ops/prod/com/cfs/v2.3/monthly/cdas.202303/monthly/egyh01.gdas.202303
++ tail -n1
482:172627284:d=23030100:COVVVVV:kpds5=220:kpds6=100:kpds7=1:TR=113:P1=1:P2=6:TimeU=1:1 mb:1hr fcst:ave@6hr:NAve=124
++ echo

++ /apps/ops/prod/libs/intel/19.1.3.304/grib_util/1.2.2/bin/copygb -x /lfs/h1/ops/prod/com/cfs/v2.3/monthly/cdas.202303/monthly/egyh01.gdas.202303 /lfs/h2/emc/global/noscrub/Jack.Woollen/egyfix/gribin
++ /lfs/h1/ops/prod/packages/cfs.v2.3.3/exec/cfs_cgrib2 -g12 -p40 /lfs/h2/emc/global/noscrub/Jack.Woollen/egyfix/gribin /lfs/h2/emc/global/noscrub/Jack.Woollen/egyfix/egyh01.gdas.202303.grib2
error: too few guard bits (need at least 5)
cannot encode main body
jpc_encode failed
 jpc_encode return = -1 
 jpcpack: ERROR Packing JPC= -3
 jpcpack: Retrying....
error: too few guard bits (need at least 5)
cannot encode main body
jpc_encode failed
 jpc_encode return = -1 
 jpcpack: Retry Failed.
  ERROR adding GRIB2 field =           10
++ echo

++ wgrib2 /lfs/h2/emc/global/noscrub/Jack.Woollen/egyfix/egyh01.gdas.202303.grib2
++ tail -n1
481:57363862:d=2023030100:COVVVVV:1 mb:21@6 hour ???(1-6 hour ave fcst),missing=0:

**Comment by edwardhartnett** [comment]
OK, have done several releases since then and I am about to do another round of releases. Many bugs have been fixed including some with JPEG. We need to try with the upcoming releases to see if we have fixed this...

**Comment by edwardhartnett** [comment]
I have done a new release of g2. @jack-woollen it will be installed everywhere in a few days. Could you try it out to see if these problems are resolved?

**Comment by jack-woollen** [comment]
@edwardhartnett I'll give it a shot. Its an intermittent problem but I'll see if I can make it fail or not. So it will be installed on wcoss2 in a couple days?

**Comment by edwardhartnett** [comment]
OK, I will close this issue and we can reopen if it recurs. @jack-woollen remember, if it happens, we need the exact data file so we can write tests around it.
