### ISSUE TITLE
update README to document dependencies on bacio and w3emc

### ISSUE THREAD

**Issue by stephentjemkes** [NOAA-EMC/NCEPLIBS-g2#436]
Hi,
I am installing the upp package on my local machine, and the first and second pass failed because of missing libraries although all libraries from the emc stack were installed.

going over the different steps once more, i noted that the  bacio library has a statement that the g2 library is using the bacio library. This to me reads like that there is a dependency on the bacio library. this dependency is not mentioned in the installation instructions. 

That suggests a confusion, meaning the upp installation suggests to install the g2 library first, (as it is on the top of the to-be-installed libraries) first, and bacio is listed in the middle. 

If there is a dependency on bacio (wihch would be consistent with the description of the bacio installation guide) could you add this to the dependency list? 

thanks
stephen

**Comment by edwardhartnett** [comment]
Yes, you are correct. We will fix the documentation.

bacio is required for g2 and must be installed first.

**Comment by stephentjemkes** [comment]
Nice thank you for the reply,
Stephen.
