### ISSUE TITLE
need to update based on WMO documentation

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-g2#47]
need to update based on WMO documentation

**Comment by edwardhartnett** [comment]
I have no idea what this issue means. ;-) @Hang-Lei-NOAA do you?

**Comment by Hang-Lei-NOAA** [comment]
This means that once there is WMO update, we have to update the library.

**Comment by edwardhartnett** [comment]
And has there been a WMO update? If so, where do we get the info?

**Comment by Hang-Lei-NOAA** [comment]
Usually, after some time (uncertainty), WMO may change/ modify some code
(used for recording weather).
When operations use the observation data, they will notice that and ask us
to update it.

**Comment by edwardhartnett** [comment]
OK, so is there a current update pending?

**Comment by Hang-Lei-NOAA** [comment]
No

**Comment by edwardhartnett** [comment]
OK, I'll close this issue, and we'll open one when we have something to do...
