### ISSUE TITLE
Add spack configuration file for next release

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-g2#48]
Add spack configuration file for next release

**Comment by kgerheiser** [comment]
Spack configuration files don't live in the target library's repo. They are maintained in Spack. I don't think this issue should be part of this repo. We have added NCEPLIBS to Spack in the NCEP fork of Spack.

**Comment by edwardhartnett** [comment]
OK, makes sense.
