### ISSUE TITLE
Repeat declarations of getidx causes bug

### ISSUE THREAD

**Issue by kgerheiser** [NOAA-EMC/NCEPLIBS-g2#49]
There are two files: `getidx.f` and `getidxes.f`

And they both declare the same subroutine `getidx`, which are nearly exactly the same.

However, this line is different between them:

https://github.com/NOAA-EMC/NCEPLIBS-g2/blob/25457ac15b6ee80adc2308d598ac9c40028c6001/src/getidxes.f#L95

and

https://github.com/NOAA-EMC/NCEPLIBS-g2/blob/25457ac15b6ee80adc2308d598ac9c40028c6001/src/getidx.f#L98

One checks if `lugb` is greater than `100` and the other checks if it's greater than `9999`.

Depending on the order of compilation (or maybe order of the symbols in the library?) either could be picked up. 

This causes a bug as reported here (https://github.com/NOAA-EMC/hpc-stack/issues/212) when `lugb` equals 201 the one version returns an error, but the other is successful.

@BoiVuong-NOAA do you know why both of these files declare `getidx`, and can you confirm that `getidxes.f` is the correct one?

**Comment by BoiVuong-NOAA** [comment]
Kyle,
The getidx.f is currently in-use in calling routines in g2 library.  We can get it off getidxes.f, if we have a chance.
I think it is not a bug in getidx.f in NOAA-EMC/hps-statck#212.   User can not use the same unit file number for opening the same file for multiple times.  Each file must have their own unit file number.
Thanks,
Boi

**Comment by kgerheiser** [comment]
Is using the same file number the issue here? Is that where `lugb` comes from? In the test case I was given `lugb` equals 201, so the check against ` > 100` fails and throws an error, while if you compare to 9999 it works.

Is the comparison of `> 100` or `> 9999` correct?

**Comment by kgerheiser** [comment]
I see, it's just a file unit, and it was set to 201, which is allowable in Fortran. I don't think comparing to 100 is correct, and neither is 9999. 

Why even do that check? What should be done is an `inquire` to check that it points to an open file instead of some arbitrary number comparison.

**Comment by BoiVuong-NOAA** [comment]
Kyle,

It checks for > 9999. Because the subroutine is calling getidx not 
calling routine getidxes.

**Comment by BoiVuong-NOAA** [comment]
Yes, You are correct.

**Comment by kgerheiser** [comment]
Should there be a subroutine called `getidxes` because in `getidxes.f` and `getidx.f` the subroutine is called `getidx`.

**Comment by BoiVuong-NOAA** [comment]
None of routines are calling getidxes.   I left it their in case someone 
wants to fall back the old way to use same file for all open a file.  
Now, All of models are opening a file with a new file unit number.

**Comment by BijuThomas-NOAA** [comment]
Boi,
When I call the subroutine getgb2, it works fine if LUGB(unit number of the  GRIB data file) <= 100 (thanks to Kyle for pointing this). But if it is >100, I get the error code 96(Error reading index file)

**Comment by BoiVuong-NOAA** [comment]
Thomas,
What is you unit file number for lugi ? Can you create a test case on Hera ?  I do not have access to Jet.
Thanks,
Boi

**Comment by BijuThomas-NOAA** [comment]
Boi,
Thanks. lugi is 601. Sure, I can create a test case on Hera.
Biju

**Comment by kgerheiser** [comment]
`lugi` has no bearing on the bug here. The test case is using a number > 100 for `lugb`. 

The problem is that there are two declarations of the subroutine `getidx`. Looks like `getidx` was copied and pasted into `getidxes.f` but the subroutine name was never changed.

https://github.com/NOAA-EMC/NCEPLIBS-g2/blob/25457ac15b6ee80adc2308d598ac9c40028c6001/src/getidxes.f#L2

The version of `getidx` in `getidx.f` was updated in 2016 to handle numbers up to 9999.

https://github.com/NOAA-EMC/NCEPLIBS-g2/blob/25457ac15b6ee80adc2308d598ac9c40028c6001/src/getidx.f#L20

But the declaration of `getidx` in `getidxes.f` is taking precedence and it only checks if `lugb` is > 100 instead of 9999.

https://github.com/NOAA-EMC/NCEPLIBS-g2/blob/25457ac15b6ee80adc2308d598ac9c40028c6001/src/getidxes.f#L95

I have a PR in #50 that removes the file `getidxes.f`. The implementation in `getidx.f` is the correct one and checks if > 9999 and prints an error message.

**Comment by BoiVuong-NOAA** [comment]
Thomas,
Kyle is right.  the declaration of getidx in getidxes.f is taking precedence and it only checks if lugb is > 100 instead of 9999.

**Comment by BijuThomas-NOAA** [comment]
Boi,
lugi is 601. Sure, I can create a test case on Hera.
Thanks,

**Comment by BijuThomas-NOAA** [comment]
Thanks. Please let me know when the g2 is built without getidxes.f

**Comment by kgerheiser** [comment]
Do you need a new build immediately or can you use the existing version of g2 and a `lugb` < 100 for the time being?

**Comment by BijuThomas-NOAA** [comment]
We need to use lugb > 100. Right now, we are not using G2 from hpc-stack because of this issue.

**Comment by BoiVuong-NOAA** [comment]
Thomas,
Just a question for you.  I recalled that it worked on DELL and CRAY with lugb=201. It that right ?

**Comment by BijuThomas-NOAA** [comment]
No, Same issue on all platforms (Jet, Hera, Dell, and Cray) with G2 from hpc-stack.
