### ISSUE TITLE
file src/version.inc is unused and can be removed?

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-g2#54]
It seems that file src/version.inc is unused and can be removed. True?

**Comment by Hang-Lei-NOAA** [comment]
This will be removed in next PR

**Comment by edwardhartnett** [comment]
It's OK to do a PR for just this. We don't get charged per PR, so breaking up work into different PRs helps us keep track of what is being done. Also it's fine to have and take some low-hanging fruit. Some issues are hard, some easy, and there's nothing wrong with racking up a win with an easy PR...
