### ISSUE TITLE
decide on yml vs. yaml, name of spack files and directory

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-g2#555]
@AlexanderRichert-NOAA sometimes we use *.yml, sometimes *.yaml.

Either is fine but both will cause much cursing. Let's decide which is best and use it everywhere.

We have a lot of files named spack.yml. I think we need to be more specific.

Rahul has suggested and we have set up an alternative method of spack-based testing, see NCEPLIBS-grib_util for an example. Do we need both his and yours?

**Comment by AlexanderRichert-NOAA** [comment]
In the approach currently in grib_util, it installs grib_util's dependencies through spack, then uses that to do a regular cmake-based build on grib_util. I would vote to replace that with an all-spack build.

Parenthetically, for the lower level libraries, this has the added advantage that we could easily add testing of depen**dents** into the workflow. In the case of, say, the sp library, we could tell spack to also install ip (which would be built based on the copy of sp being modified in the PR being tested), and run its unit tests, providing an immediate confirmation that the changes being made won't break this downstream. This would be as easy as adding, e.g., "ip" to the installation spec.

As far as file names, I have no yml vs. yaml preference, but that's a good point about spack.yml... How about spack_Linux.yml to differentiate from spack env config files, which then leaves the option of adding a MacOS version if we want.

**Comment by edwardhartnett** [comment]
OK, agree that we should move to your version of the spack build everywhere.

Great idea about testing with dependent packages. I do this now with g2 and grib_util - that is the g2 CI runs against the last released and the develop branch of grib_utils. THis is very useful! We should do it everywhere we can.

We certainly want to do MacOS testing with spack. 

Let's use yml everywhere, not yaml.
