### ISSUE TITLE
documentation error - there is only one section 8 in a GRIB2 message

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-g2#587]
In the documentation we have:

```
SECTION 0 - Indicator Section
SECTION 1 - Identification Section
SECTION 2 - (Local Use Section) - optional                           }
SECTION 3 - Grid Definition Section                     }            }
SECTION 4 - Product Definition Section    }             }            }(repeated)
SECTION 5 - Data Representation Section   }             }(repeated)  }
SECTION 6 - Bit-map Section               }(repeated)   }            }
SECTION 7 - Data Section                  }             }            }
SECTION 8 - End Section                   }             }            }

```

THis implies that section 8 can be repeated, but it can't. There is only one section 8 per message. 

@GeorgeGayno-NOAA and @Hang-Lei-NOAA am I correct? There can only be one section 8 in the message, corrrect?

**Comment by Hang-Lei-NOAA** [comment]
My understanding is that section 8 is the ending section of the grib file.

**Comment by GeorgeGayno-NOAA** [comment]
Adding @jbathegit, who is our GRIB expert. 

I believe that documentation describes how multiple GRIB messages can be arranged as part of a single file. For example, a file could contain multiple fields (temperature, humidity, etc). Our OPS GRIB2 data does this. In that case the end section would need to be repeated for each field. As long as each field has the same sections 0 and 1, then multiple fields can be placed in a single file.

**Comment by GeorgeGayno-NOAA** [comment]
Adding @jbathegit, who know more about GRIB than I do.

**Comment by jbathegit** [comment]
@edwardhartnett, you're correct - there can be only one Section 8 in a GRIB2 message.

Here's a screenshot straight from the horse's mouth (i.e. from WMO Manual 306, which is the official GRIB2 bible :-)

![GRIB2_sections](https://github.com/NOAA-EMC/NCEPLIBS-g2/assets/62722702/2a596edc-26ce-4cff-a49a-5d3354318fc3)
