### ISSUE TITLE
Is the spack build really doing what we think it is?

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-g2#661]
It seems to be succeeding even on a PR with broken code. Is it correctly testing the branch that is being PRed?

**Comment by AlexanderRichert-NOAA** [comment]
Can you point me to an example of a "suspicious" Spack.yml run?

**Comment by edwardhartnett** [comment]
OK, I'm an idiot. I was looking at the setup job. Of course that always works, even when the repo is broken, because it just builds the dependencies...

Never mind!
