### ISSUE TITLE
Add PDT 4.49

### ISSUE THREAD

**Issue by WenMeng-NOAA** [NOAA-EMC/NCEPLIBS-g2#725]
To encode ensemble information in metadata of aerosol fields in GRIB2 data, [PDT 4.49](https://www.nco.ncep.noaa.gov/pmb/docs/grib2/grib2_doc/grib2_temp4-49.shtml) should be added in pdstemplates.F90.

**Comment by edwardhartnett** [comment]
I think we want to do a branch of the last release, instead of doing this directly on the develop branch.

**Comment by WenMeng-NOAA** [comment]
@edwardhartnett @lipan-NOAA has the changes for PDT 4.49. He could submit a PR for source code update only. Please let him know which branch his PR should target.

**Comment by edwardhartnett** [comment]
OK, I already have the changes up on a PR. Please @lipan-NOAA take a look and see if it looks correct.

Always target develop branch for any changes to a NCEPLIBS repo.

**Comment by WenMeng-NOAA** [comment]
> OK, I already have the changes up on a PR. Please @lipan-NOAA take a look and see if it looks correct.
> 
> Always target develop branch for any changes to a NCEPLIBS repo.

@edwardhartnett That's great that you have a PR for this update. Please assign @lipan-NOAA to review your PR. Thanks!
