### ISSUE TITLE
update gh-pages branch with newly built documentation

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-g2#73]
@Hang-Lei-NOAA do you know how to update the gh-pages branch with newly built documenation?

Normally we only do this when we release a new version, but it's also worth doing from time to time when doing these documentation fixes, because it gets the built documents out there where people can see them.

If you know how to do it, you can do so whenever you like during this documentation campaign (but in normal times, you should only do it when a new version is released).

If you don't know how, ask, and I will dig up the instructions...

**Comment by Hang-Lei-NOAA** [comment]
Yes, I know that.
I will address it and post it on the web for review.
Then I will change it back to C>
update

**Comment by kgerheiser** [comment]
Did this as part of the release.
