### ISSUE TITLE
Clean up of docs/user_guide.md

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-g2#81]
The file docs/user_guide.md is the landing page for the doxygen generated documentation. It contains a high-level description of the library.

The current page is the first pass of converting some legacy documentation, and it needs some more work.

Most importantly, all functions/subroutines need to have "()" added after their name, so that they get hyperlined to the proper subprogram documentation. For example:

`To start a new GRIB2 message, call subroutine GRIBCREATE. GRIBCREATE encodes Sections 0 and 1 at the beginning of the message. This routine must be used to create each message.
`

Should become:

`To start a new GRIB2 message, call subroutine GRIBCREATE(). GRIBCREATE() encodes Sections 0 and 1 at the beginning of the message. This routine must be used to create each message.
`

This will cause the subprogram name GRIBCREATE to automatically be linked, so that the user can click on it and jump to the documentation for GRIBCREATE. This needs to happen with all subprogram names in the document.

Further down in the user_guide.md, there is some example code which is not being formatted correctly in doxygen, and that needs to be fixed.

**Comment by edwardhartnett** [comment]
Also somehow the landing page vs. "user guide" page in the generated docs is somehow messed up. We have a nice landing page, but the user guide page is empty.

Instead, we either want the "user guide" to disappear from the list of pages, and just have the landing page be the user guide page...

**Comment by Hang-Lei-NOAA** [comment]
User guide shown in list of pages has been adjusted.
"user guide" is starting to edit.
